testonly: False
with-expecter: True
unroll-variadic: False
packages:
  github.com/metal-toolbox/conditionorc/internal/store:
    config:
      dir: internal/store
      fileName: "mock_{{.InterfaceName | firstLower}}.go"
      inpackage: True
    interfaces:
      Repository:
  github.com/metal-toolbox/conditionorc/internal/fleetdb:
    config:
      dir: internal/fleetdb
      fileName: "mock_{{.InterfaceName | firstLower}}.go"
      inpackage: True
    interfaces:
      FleetDB:
