name: lint, test and build image
on: [pull_request, push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --config .golangci.yml --timeout 2m
          version: v1.57.1
          skip-cache: true

      - name: Test
        run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: build binary
        run: make build-linux

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Alloy Docker image - no push
        id: dockerbuild-conditionorc
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ghcr.io/metal-toolbox/conditionorc:latest
          file: Dockerfile

      - name: Scan image
        id: scan-image
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/metal-toolbox/conditionorc:latest
          acs-report-enable: true
          fail-build: false

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
        # This should run even if we fail the container scan
        if: always()
